/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    // 用于覆盖tailwindcss的默认配置
    colors: {
      white: 'var(--el-color-white)',
      primary: {
        DEFAULT: 'var(--el-color-primary)',
        'light-1': 'var(--el-color-primary-light-1)',
        'light-2': 'var(--el-color-primary-light-2)',
        'light-3': 'var(--el-color-primary-light-3)',
        'light-4': 'var(--el-color-primary-light-5)',
        'light-5': 'var(--el-color-primary-light-5)',
        'light-6': 'var(--el-color-primary-light-6)',
        'light-7': 'var(--el-color-primary-light-7)',
        'light-8': 'var(--el-color-primary-light-8)',
        'light-9': 'var(--el-color-primary-light-9)',
        'dark-2': 'var(--el-color-primary-dark-2)',
      },
      success: {
        DEFAULT: 'var(--el-color-success)',
        'light-3': 'var(--el-color-success-light-3)',
        'light-5': 'var(--el-color-success-light-5)',
        'light-7': 'var(--el-color-success-light-7)',
        'light-8': 'var(--el-color-success-light-8)',
        'light-9': 'var(--el-color-success-light-9)',
        'dark-2': 'var(--el-color-success-dark-2)',
      },
      warning: {
        DEFAULT: 'var(--el-color-warning)',
        'light-3': 'var(--el-color-warning-light-3)',
        'light-5': 'var(--el-color-warning-light-5)',
        'light-7': 'var(--el-color-warning-light-7)',
        'light-8': 'var(--el-color-warning-light-8)',
        'light-9': 'var(--el-color-warning-light-9)',
        'dark-2': 'var(--el-color-warning-dark-2)',
      },
      danger: {
        DEFAULT: 'var(--el-color-danger)',
        'light-3': 'var(--el-color-danger-light-3)',
        'light-5': 'var(--el-color-danger-light-5)',
        'light-7': 'var(--el-color-danger-light-7)',
        'light-8': 'var(--el-color-danger-light-8)',
        'light-9': 'var(--el-color-danger-light-9)',
        'dark-2': 'var(--el-color-danger-dark-2)',
      },
      error: {
        DEFAULT: 'var(--el-color-error)',
        'light-3': 'var(--el-color-error-light-3)',
        'light-5': 'var(--el-color-error-light-5)',
        'light-7': 'var(--el-color-error-light-7)',
        'light-8': 'var(--el-color-error-light-8)',
        'light-9': 'var(--el-color-error-light-9)',
        'dark-2': 'var(--el-color-error-dark-2)',
      },
      info: {
        DEFAULT: 'var(--el-color-info)',
        'light-3': 'var(--el-color-info-light-3)',
        'light-5': 'var(--el-color-info-light-5)',
        'light-7': 'var(--el-color-info-light-7)',
        'light-8': 'var(--el-color-info-light-8)',
        'light-9': 'var(--el-color-info-light-9)',
        'dark-2': 'var(--el-color-info-dark-2)',
      },
      body: 'var(--el-bg-color)',
      page: 'var(--el-bg-color-page)',
      'tx-primary': 'var(--el-text-color-primary)',
      'tx-regular': 'var(--el-text-color-regular)',
      'tx-secondary': 'var(--el-text-color-secondary)',
      'tx-placeholder': 'var(--el-text-color-placeholder)',
      'tx-disabled': 'var(--el-text-color-disabled)',
      br: 'var(--el-border-color)',
      'br-light': 'var(--el-border-color-light)',
      'br-extra-light': 'var(--el-border-color-extra-light)',
      'br-dark': 'var( --el-border-color-dark)',
      fill: 'var(--el-fill-color)',
      'fill-light': 'var(--el-fill-color-light)',
      'fill-lighter': 'var(--el-fill-color-lighter)',
      mask: 'var(--el-mask-color)',
    },
    fontFamily: {
      sans: [
        'Fira Code',
        'PingFang SC',
        'Arial',
        'Hiragino Sans GB',
        'Microsoft YaHei',
        'Simsun',
        'sans-serif',
      ],
    },
    extend: {
      boxShadow: {
        el: 'var(--el-box-shadow)',
        normal: '0px 0px 14px rgba(0, 0, 0, 0.07)',
      },
      backgroundColor: {
        el: 'var(--el-bg-color)',
        'el-page': 'var(--el-bg-color-page)',
      },
      borderColor: {
        el: 'var(--el-border-color)',
        'el-light': 'var(--el-border-color-light)',
        'el-extra-light': 'var(--el-border-color-extra-light)',
        'el-dark': 'var(--el-border-color-dark)',
      },
    },
  },
  plugins: [],
}
